import { useEffect, useState } from 'react';
import { Alert, Box, Button, Dialog, DialogActions, DialogContent, DialogTitle, FormControl, FormControlLabel, InputLabel, MenuItem, Paper, Radio, RadioGroup, Select, Stack, Typography } from '@mui/material';
import type { CustomerData } from '../../types/customer.types';
import { customerApi } from '../../api/customer.api';
import { useUserPreferences } from '../../contexts/UserPreferencesContext';

type Preview = Awaited<ReturnType<typeof customerApi.mergePreview>>;
export default function CustomerMergeDialog({ open, customers, onClose, onMerged }: { open: boolean; customers: CustomerData[]; onClose: () => void; onMerged: () => void }) {
  const { t } = useUserPreferences(); const [targetId, setTargetId] = useState(''); const [preview, setPreview] = useState<Preview | null>(null); const [choices, setChoices] = useState<Record<string, 'source' | 'target'>>({}); const [keepProfileId, setKeepProfileId] = useState(''); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const sourceId = customers.find(customer => customer.customerId !== targetId)?.customerId || '';
  useEffect(() => { if (open && customers.length === 2) setTargetId(current => customers.some(customer => customer.customerId === current) ? current : customers[1].customerId); }, [open, customers]);
  useEffect(() => { if (!open || !sourceId || !targetId) return; setPreview(null); void customerApi.mergePreview(sourceId, targetId).then(result => { setPreview(result); setChoices(Object.fromEntries(result.fields.map(field => [field.field, field.recommended]))); setKeepProfileId(result.profiles.find(profile => profile.customerId === targetId)?.profileId || result.profiles[0]?.profileId || ''); }).catch(() => setError(t('customers.merge.loadError'))); }, [open, sourceId, targetId, t]);
  const apply = async () => { if (!preview) return; setSaving(true); setError(''); try { const values = Object.fromEntries(preview.fields.map(field => [field.field, choices[field.field] === 'source' ? field.source : field.target])); await customerApi.mergeCustomers({ sourceCustomerId: sourceId, targetCustomerId: targetId, values, keepProfileId: keepProfileId || undefined }); onMerged(); onClose(); } catch { setError(t('customers.merge.error')); } finally { setSaving(false); } };
  return <Dialog open={open} onClose={() => !saving && onClose()} fullWidth maxWidth="md"><DialogTitle>{t('customers.merge.title')}</DialogTitle><DialogContent><Alert severity="warning" sx={{ mb: 2 }}>{t('customers.merge.warning')}</Alert>{error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}<FormControl fullWidth sx={{ mb: 2 }}><InputLabel>{t('customers.merge.target')}</InputLabel><Select value={targetId} label={t('customers.merge.target')} onChange={event => setTargetId(event.target.value)}>{customers.map(customer => <MenuItem key={customer.customerId} value={customer.customerId}>{customer.customerName} {customer.customerLastName}</MenuItem>)}</Select></FormControl><Stack spacing={1}>{preview?.fields.map(field => <Paper key={field.field} variant="outlined" sx={{ p: 1.5 }}><Typography fontWeight={750}>{field.field}</Typography><RadioGroup row value={choices[field.field] || field.recommended} onChange={event => setChoices(current => ({ ...current, [field.field]: event.target.value as 'source' | 'target' }))}><FormControlLabel value="target" control={<Radio />} label={`${t('customers.merge.keepTarget')}: ${String(field.target ?? '—')}`} /><FormControlLabel value="source" control={<Radio />} label={`${t('customers.merge.keepSource')}: ${String(field.source ?? '—')}`} /></RadioGroup></Paper>)}</Stack>{Boolean(preview?.profiles.length) && <Box mt={2}><FormControl fullWidth><InputLabel>{t('customers.merge.keepProfile')}</InputLabel><Select value={keepProfileId} label={t('customers.merge.keepProfile')} onChange={event => setKeepProfileId(event.target.value)}>{preview?.profiles.map(profile => <MenuItem key={profile.profileId} value={profile.profileId}>{profile.displayName} · {profile.status}</MenuItem>)}</Select></FormControl></Box>}</DialogContent><DialogActions><Button onClick={onClose} disabled={saving}>{t('common.cancel')}</Button><Button variant="contained" color="warning" onClick={() => void apply()} disabled={saving || !preview}>{t('customers.merge.confirm')}</Button></DialogActions></Dialog>;
}
