import { useCallback, useEffect, useState } from 'react';
import { Alert, Button, Card, CardContent, Chip, Stack, Typography } from '@mui/material';
import { useSearchParams } from 'react-router-dom';
import { API_URL } from '../../utils/runtimeEnv';
import feedback from '../../services/feedback.service';
import { PageHeader, PageLoading, PageShell } from '../../components/PageState';
import { useUserPreferences } from '../../contexts/UserPreferencesContext';
type RequestItem = { requestId: string; email: string; userName: string; userLastName: string; status: string; verifiedAt?: string; createdAt: string };
export default function RegistrationRequestsPage() {
  const { t } = useUserPreferences();
  const [params] = useSearchParams(); const highlight = params.get('requestId'); const [items, setItems] = useState<RequestItem[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(false);
  const load = useCallback(() => fetch(`${API_URL}/user-management/registration-requests`, { credentials: 'include' }).then(r => { if (!r.ok) throw new Error(); return r.json(); }).then(p => { setItems(p.data || []); setError(false); }).catch(() => setError(true)).finally(() => setLoading(false)), []);
  useEffect(() => { void load(); }, [load]);
  const decide = async (item: RequestItem, action: 'approve'|'reject') => { const result = await feedback.confirm({ title: t(action === 'approve' ? 'uat.registration.approveTitle' : 'uat.registration.rejectTitle'), message: `${item.userName} ${item.userLastName} · ${item.email}`, confirmLabel: t(action === 'approve' ? 'uat.registration.approve' : 'uat.registration.reject'), cancelLabel: t('uat.registration.cancel'), destructive: action === 'reject' }); if (!result.isConfirmed) return; const response = await fetch(`${API_URL}/user-management/registration-requests/${item.requestId}/${action}`, { method: 'POST', credentials: 'include', headers: { 'Content-Type': 'application/json' }, body: '{}' }); if (!response.ok) { void feedback.error(t('uat.registration.actionError')); return; } void feedback.success(t(action === 'approve' ? 'uat.registration.approved' : 'uat.registration.rejected')); void load(); };
  return <PageShell><PageHeader title={t('uat.registration.title')} subtitle={t('uat.registration.subtitle')} />{error && <Alert severity="error">{t('feedback.networkHelp')}</Alert>}{loading ? <PageLoading rows={3} label={t('uat.registration.loading')} /> : <Stack gap={1.5}>{items.map(item => <Card key={item.requestId} variant="outlined" sx={{ borderRadius: 3, outline: item.requestId === highlight ? '3px solid' : undefined, outlineColor: 'primary.main' }}><CardContent><Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" gap={2}><Stack><Typography variant="h6">{item.userName} {item.userLastName}</Typography><Typography color="text.secondary">{item.email}</Typography><Typography variant="caption">{new Date(item.createdAt).toLocaleString()}</Typography></Stack><Stack direction="row" alignItems="center" gap={1}><Chip label={item.status} />{item.status === 'pending_approval' && <><Button variant="contained" onClick={() => void decide(item, 'approve')}>{t('uat.registration.approve')}</Button><Button color="error" variant="outlined" onClick={() => void decide(item, 'reject')}>{t('uat.registration.reject')}</Button></>}</Stack></Stack></CardContent></Card>)}{!items.length && <Alert severity="info">{t('uat.registration.empty')}</Alert>}</Stack>}</PageShell>;
}
