import { useState } from 'react';
import { Alert, Box, Button, MenuItem, Paper, Stack, TextField, Typography } from '@mui/material';
import { apiConfig } from '../../api/config';
import { useUserPreferences } from '../../contexts/UserPreferencesContext';
export default function PrivacyRequestPage() {
  const { t } = useUserPreferences();
  const [form, setForm] = useState({ email: '', requestType: 'access', message: '', website: '' }); const [state, setState] = useState<'idle'|'sending'|'sent'|'error'>('idle');
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setState('sending'); try { const response = await fetch(`${apiConfig.baseURL}/privacy/requests`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); if (!response.ok) throw new Error(); setState('sent'); } catch { setState('error'); } };
  return <Box sx={{ minHeight: '100vh', p: 3, bgcolor: 'background.default' }}><Paper component="form" onSubmit={submit} variant="outlined" sx={{ maxWidth: 640, mx: 'auto', p: 4, borderRadius: 4 }}><Stack gap={2}><Typography variant="h4" fontWeight={900}>{t('uat.privacyRequest.title')}</Typography><Typography color="text.secondary">{t('uat.privacyRequest.help')}</Typography>{state === 'sent' && <Alert severity="success">{t('uat.privacyRequest.sent')}</Alert>}{state === 'error' && <Alert severity="error">{t('uat.privacyRequest.error')}</Alert>}<TextField required type="email" label={t('common.emailAddress')} value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} /><TextField select label={t('uat.privacyRequest.type')} value={form.requestType} onChange={e => setForm({ ...form, requestType: e.target.value })}><MenuItem value="access">{t('uat.privacyRequest.access')}</MenuItem><MenuItem value="correction">{t('uat.privacyRequest.correction')}</MenuItem><MenuItem value="deletion">{t('uat.privacyRequest.deletion')}</MenuItem><MenuItem value="withdrawal">{t('uat.privacyRequest.withdrawal')}</MenuItem><MenuItem value="other">{t('uat.privacyRequest.other')}</MenuItem></TextField><TextField multiline minRows={4} label={t('uat.privacyRequest.details')} value={form.message} onChange={e => setForm({ ...form, message: e.target.value })} /><TextField sx={{ display: 'none' }} tabIndex={-1} value={form.website} onChange={e => setForm({ ...form, website: e.target.value })} /><Button type="submit" variant="contained" disabled={state === 'sending'}>{t('uat.privacyRequest.submit')}</Button></Stack></Paper></Box>;
}
