import { useCallback, useEffect, useState } from 'react';
import { Alert, Button, Card, CardContent, MenuItem, Select, Stack, Typography } from '@mui/material';
import { Link as RouterLink } from 'react-router-dom';
import { useSearchParams } from 'react-router-dom';
import { API_URL } from '../../utils/runtimeEnv';
import { PageHeader, PageLoading, PageShell } from '../../components/PageState';
import { useUserPreferences } from '../../contexts/UserPreferencesContext';
type Item = { requestId: string; email: string; requestType: string; message?: string; status: string; createdAt: string };
export default function PrivacyRequestsPage() { const { t } = useUserPreferences(); const [params] = useSearchParams(); const [items, setItems] = useState<Item[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(false); const load = useCallback(() => fetch(`${API_URL}/privacy/requests`, { credentials: 'include' }).then(r => { if (!r.ok) throw new Error(); return r.json(); }).then(p => { setItems(p.data || []); setError(false); }).catch(() => setError(true)).finally(() => setLoading(false)), []); useEffect(() => { void load(); }, [load]); const update = async (id: string, status: string) => { await fetch(`${API_URL}/privacy/requests/${id}`, { method: 'PATCH', credentials: 'include', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ status }) }); void load(); }; return <PageShell><PageHeader title={t('uat.privacyInbox.title')} subtitle={t('uat.privacyInbox.subtitle')} />{error && <Alert severity="error">{t('uat.privacyInbox.error')}</Alert>}{loading ? <PageLoading rows={3} label={t('uat.privacyInbox.loading')} /> : items.length === 0 ? <Alert severity="info" action={<Button component={RouterLink} to="/privacy/request" color="inherit">{t('uat.privacyInbox.openForm')}</Button>}>{t('uat.privacyInbox.empty')}</Alert> : <Stack gap={1.5}>{items.map(item => <Card key={item.requestId} variant="outlined" sx={{ borderRadius: 3, outline: params.get('requestId') === item.requestId ? '3px solid' : undefined, outlineColor: 'primary.main' }}><CardContent><Stack direction={{ xs: 'column', md: 'row' }} justifyContent="space-between" gap={2}><Stack><Typography variant="h6">{item.requestType}</Typography><Typography>{item.email}</Typography><Typography color="text.secondary">{item.message || t('uat.privacyInbox.noDetails')}</Typography><Typography variant="caption">{new Date(item.createdAt).toLocaleString()}</Typography></Stack><Select size="small" value={item.status} onChange={e => void update(item.requestId, e.target.value)} sx={{ minWidth: 160, alignSelf: 'flex-start' }}><MenuItem value="open">{t('uat.privacyInbox.open')}</MenuItem><MenuItem value="in_progress">{t('uat.privacyInbox.progress')}</MenuItem><MenuItem value="completed">{t('uat.privacyInbox.completed')}</MenuItem><MenuItem value="rejected">{t('uat.privacyInbox.rejected')}</MenuItem></Select></Stack></CardContent></Card>)}</Stack>}</PageShell>; }
