import { useEffect, useState } from 'react';
import { Alert, Button, Chip, Divider, Paper, Stack, TextField, Typography } from '@mui/material';
import { publicProfileApi } from '../../api/publicProfile.api';
import type { ProfileDomain, ProfileLinkCheck, ProfileRevision, PublicProfileRecord } from '../../types/publicProfile.types';
import { parseProfileLinksCsv } from '../../utils/profileLinkImport';
import { useUserPreferences } from '../../contexts/UserPreferencesContext';

export default function ProfileOperationsPanel({ profile, onUpdated }: { profile: PublicProfileRecord; onUpdated: (profile: PublicProfileRecord) => void }) {
  const { t } = useUserPreferences(); const [checks, setChecks] = useState<ProfileLinkCheck[]>([]); const [revisions, setRevisions] = useState<ProfileRevision[]>([]); const [domains, setDomains] = useState<ProfileDomain[]>([]); const [hostname, setHostname] = useState(''); const [notice, setNotice] = useState(''); const [error, setError] = useState('');
  const refresh = async () => { const [history, domainRows] = await Promise.all([publicProfileApi.revisions(profile.profileId).catch(() => []), profile.capabilities?.canManageDomain ? publicProfileApi.domains(profile.profileId).catch(() => []) : Promise.resolve([])]); setRevisions(history); setDomains(domainRows); };
  useEffect(() => { void refresh(); }, [profile.profileId]);
  const importFile = async (file?: File) => { if (!file) return; const parsed = parseProfileLinksCsv(await file.text()); if (!parsed.links.length) { setError(t('profile.import.invalid')); return; } const saved = await publicProfileApi.update(profile.profileId, { ...profile, links: [...profile.links, ...parsed.links].slice(0, 12), revisionReason: 'manual' } as any); onUpdated(saved); setNotice(t('profile.import.applied', { count: parsed.links.length })); if (parsed.errors.length) setError(t('profile.import.partial', { count: parsed.errors.length })); };
  return <Paper variant="outlined" sx={{ mt: 2, p: 2, borderRadius: 4 }}><Typography variant="h6" fontWeight={850}>{t('profile.operations.title')}</Typography>{notice && <Alert severity="success" sx={{ mt: 1 }}>{notice}</Alert>}{error && <Alert severity="warning" sx={{ mt: 1 }}>{error}</Alert>}
    <Stack direction={{ xs: 'column', sm: 'row' }} gap={1} mt={2}><Button variant="outlined" onClick={async () => { setChecks(await publicProfileApi.checkLinks(profile.profileId)); }}>{t('profile.links.check')}</Button><Button component="label" variant="outlined">{t('profile.import.csv')}<input hidden type="file" accept=".csv,text/csv" onChange={e => { void importFile(e.target.files?.[0]); e.target.value = ''; }}/></Button><Button variant="outlined" onClick={async () => { const templates = [{ platform: 'facebook', label: 'Facebook', url: '' },{ platform: 'instagram', label: 'Instagram', url: '' },{ platform: 'line', label: 'LINE', url: '' }]; const links = templates.map((item, index) => ({ ...item, sortOrder: profile.links.length + index, isVisible: false })); const saved = await publicProfileApi.update(profile.profileId, { ...profile, links: [...profile.links, ...links].slice(0,12), revisionReason: 'manual' } as any); onUpdated(saved); }}>{t('profile.import.template')}</Button></Stack>
    {!!checks.length && <Stack direction="row" flexWrap="wrap" gap={1} mt={1.5}>{checks.map(check => <Chip key={check.checkId} color={check.status === 'ok' ? 'success' : check.status === 'invalid' ? 'error' : 'warning'} label={`${check.targetKey}: ${check.detail || check.status}`}/>)}</Stack>}
    <Divider sx={{ my: 2 }}/><Typography fontWeight={800}>{t('profile.revisions.title')}</Typography><Stack direction="row" flexWrap="wrap" gap={1} mt={1}>{revisions.slice(0,6).map(item => <Button size="small" key={item.revisionId} variant="text" onClick={async () => { const restored = await publicProfileApi.restoreRevision(profile.profileId, item.revisionId); onUpdated(restored); await refresh(); }}>{t('profile.revisions.restore', { version: item.version })}</Button>)}</Stack>
    {profile.capabilities?.canManageDomain && <><Divider sx={{ my: 2 }}/><Typography fontWeight={800}>{t('profile.domains.title')}</Typography><Stack direction={{ xs: 'column', sm: 'row' }} gap={1} mt={1}><TextField size="small" fullWidth label={t('profile.domains.hostname')} value={hostname} onChange={e => setHostname(e.target.value)}/><Button disabled={!hostname} onClick={async () => { try { await publicProfileApi.addDomain(profile.profileId, hostname); setHostname(''); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : t('profile.domains.error')); } }}>{t('common.add')}</Button></Stack><Stack spacing={1} mt={1}>{domains.map(domain => <Stack key={domain.domainId} direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" alignItems={{ sm: 'center' }}><Typography>{domain.hostname}</Typography><Stack direction="row" gap={1} alignItems="center"><Chip size="small" label={domain.isCanonical ? t('profile.domains.canonical') : domain.status}/>{domain.status !== 'active' && <Button size="small" onClick={async () => { await publicProfileApi.verifyDomain(profile.profileId, domain.domainId); await refresh(); }}>{t('profile.domains.verify')}</Button>}{domain.status === 'active' && !domain.isCanonical && <Button size="small" onClick={async () => { await publicProfileApi.setCanonicalDomain(profile.profileId, domain.domainId); await refresh(); }}>{t('profile.domains.makeCanonical')}</Button>}<Button size="small" color="error" onClick={async () => { if (!window.confirm(t('profile.domains.removeConfirm'))) return; await publicProfileApi.removeDomain(profile.profileId, domain.domainId); await refresh(); }}>{t('common.delete')}</Button></Stack></Stack>)}</Stack></>}
  </Paper>;
}
