import React from 'react';
import { Box, Chip, Typography } from '@mui/material';
import AchievementArtwork from '../AchievementArtwork';
import type { AchievementRarity } from '../../api/reward.api';
export type AchievementShareFormat='square'|'story';
export interface AchievementShareEntry { title:string; description:string; artworkKey:string; rarity:AchievementRarity; earnedDate:string }
interface Props { entry:AchievementShareEntry; format:AchievementShareFormat; brandLabel:string; achievementLabel:string }
const AchievementShareCard=React.forwardRef<HTMLDivElement,Props>(function AchievementShareCard({entry,format,brandLabel,achievementLabel},ref){const story=format==='story';return <Box ref={ref} data-testid={`achievement-share-${format}`} sx={{width:1080,height:story?1920:1080,position:'relative',overflow:'hidden',boxSizing:'border-box',display:'grid',placeItems:'center',p:story?'220px 110px':'110px',color:'#edf7ef',background:'radial-gradient(circle at 50% 30%,#416950 0,#1c3226 34%,#0e1812 72%)','&::before':{content:'""',position:'absolute',inset:story?70:54,border:'2px solid rgba(208,232,215,.2)',borderRadius:story?70:54,boxShadow:'inset 0 0 100px rgba(132,196,151,.08)'}}}><Box textAlign="center" width="100%" maxWidth={800} zIndex={1}><Typography sx={{fontSize:28,letterSpacing:'.24em',fontWeight:800,color:'#a9cbb2'}}>{brandLabel}</Typography><Box sx={{display:'grid',placeItems:'center',my:story?12:7,transform:'scale(2.4)'}}><AchievementArtwork artworkKey={entry.artworkKey} rarity={entry.rarity} size={120}/></Box><Chip label={entry.rarity.toUpperCase()} sx={{height:44,px:1.5,fontSize:20,fontWeight:850,letterSpacing:'.12em',bgcolor:'rgba(219,241,225,.12)',color:'#dff5e5'}}/><Typography sx={{mt:4,fontSize:story?74:62,lineHeight:1.05,fontWeight:950}}>{entry.title}</Typography><Typography sx={{mt:3,fontSize:story?38:32,lineHeight:1.4,color:'#c1d6c7'}}>{entry.description}</Typography><Typography sx={{mt:5,fontSize:24,color:'#91ad99'}}>{entry.earnedDate}</Typography></Box><Typography sx={{position:'absolute',bottom:story?90:62,fontSize:24,letterSpacing:'.18em',color:'#91ad99'}}>{achievementLabel}</Typography></Box>});
export default AchievementShareCard;
